/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./../src/components/Avatar/src/Avatar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Fullscreen: typeof import('./../src/components/Fullscreen/src/Fullscreen.vue')['default']
    LocaleSwitch: typeof import('./../src/components/LocaleSwitch/src/LocaleSwitch.vue')['default']
    Logo: typeof import('./../src/components/Logo/src/Logo.vue')['default']
    Menu: typeof import('./../src/components/Menu/src/Menu.vue')['default']
    RenderVertical: typeof import('./../src/components/Menu/src/components/RenderVertical.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsView: typeof import('./../src/components/TagsView/src/TagsView.vue')['default']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch/src/ThemeSwitch.vue')['default']
    VxContainer: typeof import('./../src/components/VxContainer/src/VxContainer.vue')['default']
    VxIcon: typeof import('./../src/components/VxIcon/src/VxIcon.vue')['default']
    VXIcon: typeof import('./../src/components/VXIcon/src/VXIcon.vue')['default']
  }
}
