/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: (typeof import("element-plus/es"))["ElConfigProvider"]
    ElDatePicker: (typeof import("element-plus/es"))["ElDatePicker"]
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: (typeof import("element-plus/es"))["ElInput"]
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: (typeof import("element-plus/es"))["ElMenu"]
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"]
    ElMenuItemGroup: (typeof import("element-plus/es"))["ElMenuItemGroup"]
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"]
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"]
    ElTag: (typeof import("element-plus/es"))["ElTag"]
    LocaleSwitch: typeof import('./../src/components/LocaleSwitch/src/LocaleSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch/src/ThemeSwitch.vue')['default']
    VxIcon: typeof import('./../src/components/VxIcon/src/VxIcon.vue')['default']
  }
}
