/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    RouterLink: (typeof import("vue-router"))["RouterLink"]
    RouterView: (typeof import("vue-router"))["RouterView"]
    ThemeSwitch: (typeof import("./components/ThemeSwitch/src/ThemeSwitch.vue"))["default"]
    VxIcon: (typeof import("./components/VxIcon/src/VxIcon.vue"))["default"]
  }
}
